Repository pabless/DGen, pull requests merged in 2018-06, with the labels that each got.

#22 AddStudent functionality added
  src/main/java/db/entities/ClassificationSystemConst.java
  src/main/java/db/mapper/DiplomaMapper.java
  src/main/java/db/mapper/EducationalComponentMapper.java
  src/main/java/db/mapper/StudentMapper.java
  src/main/java/db/services/ClassificationSystemService.java
  src/main/java/db/services/DiplomaService.java
  src/main/java/db/services/DiplomaSubjectService.java
  src/main/java/db/services/EctsCreditsService.java
  src/main/java/db/services/OfficialDurationOfProgrammeService.java
  src/main/java/db/services/PreviousDocumentService.java
  src/main/java/db/services/StudentService.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/models/Diploma.java
  src/main/resources/fxml/student.fxml
  src/main/resources/sql/drop.sql
Labels: enhancement

#23 Settings added
  src/main/java/db/entities/Diploma.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/settings.fxml
Labels: enhancement

#24 AddStudent and EditStudent functionality finished
  src/main/java/db/entities/ClassificationSystemConst.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/models/ClassificationSystem.java
  src/main/resources/fxml/student.fxml
Labels: enhancement

#25 Validation refactoring
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/utils/AlertBox.java
  src/main/java/ui/utils/Validation.java
Labels: enhancement

#27 Bug fixes
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/student.fxml
Labels: enhancement

#28 Deputat
  src/main/java/db/entities/ClassificationSystemConst.java
  src/main/java/db/mapper/EducationalComponentTemplateMapper.java
  src/main/java/db/services/BaseServiceImpl.java
  src/main/java/db/services/ClassificationSystemService.java
  src/main/java/db/services/DurationOfTrainingService.java
  src/main/java/db/services/FieldOfStudyService.java
  src/main/java/db/services/GroupService.java
  src/main/java/db/services/MainFieldService.java
  src/main/java/db/services/OfficialDurationOfProgrammeService.java
  src/main/java/db/services/PreviousDocumentService.java
  src/main/java/db/services/ProtocolService.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/java/ui/utils/AlertBox.java
  src/main/java/ui/utils/Validation.java
  src/main/resources/fxml/settings.fxml
Labels: enhancement

#29 Commit
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/resources/fxml/student.fxml
Labels: enhancement

#30 Deputat
  src/main/java/doc_utils/AppProperties.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/resources/database.properties
  src/main/resources/fxml/main.fxml
  src/main/resources/sql/db.sql
  src/main/resources/sql/general_data.sql
Labels: bug, enhancement

#31 AlertBoxes added, bug with date pickers fixed
  src/main/java/doc_utils/Main.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/utils/AlertBox.java
Labels: enhancement

#34 Deputat
  src/main/java/db/entities/PreviousDocument.java
  src/main/java/db/mapper/PreviousDocumentMapper.java
  src/main/java/db/mapper/StudentMapper.java
  src/main/java/doc_utils/DocWorker.java
  src/main/java/doc_utils/Main.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/models/PreviousDocument.java
  src/main/resources/fxml/settings.fxml
  src/main/resources/fxml/student.fxml
  src/main/resources/sql/db.sql
  src/main/resources/sql/diploma_subjects.sql
  src/main/resources/sql/diplomas.sql
  src/main/resources/sql/drop.sql
  src/main/resources/sql/educational_components(PI-14-1).sql
  src/main/resources/sql/educational_components(PIt-15-2).sql
  src/main/resources/sql/educational_components(PIt-16-3).sql
  src/main/resources/sql/educational_components(PIt-16-4).sql
  src/main/resources/sql/educational_components(PIz-14-1).sql
  src/main/resources/sql/educational_components(UPDATE national grade).sql
  src/main/resources/sql/educational_components.sql
  src/main/resources/sql/educational_components_template.sql
  src/main/resources/sql/general_data.sql
  src/main/resources/sql/pi-14-1.sql
  src/main/resources/sql/previous_document.sql
  src/main/resources/sql/protocols_TEST.sql
  src/main/resources/sql/students.sql
  src/main/resources/sql/test_data.sql
Labels: enhancement

#36 Deputat
  src/main/java/db/mapper/EducationalComponentTemplateMapMapper.java
  src/main/java/db/services/ClearDBService.java
  src/main/java/db/services/EducationalComponentService.java
  src/main/java/db/services/EducationalComponentTemplateService.java
  src/main/java/db/services/TableCleanerService.java
  src/main/java/ui/Main.java
  src/main/java/ui/controllers/FXMLEducationalComponentsController.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/models/EducationalComponent.java
  src/main/java/ui/models/EducationalComponentTemplate.java
  src/main/java/ui/models/EducationalComponentWithData.java
  src/main/java/ui/models/Student.java
  src/main/java/ui/models/TemplateWithEducationalComponents.java
  src/main/resources/fxml/educationalComponents.fxml
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/settings.fxml
  src/main/resources/log4j2.properties
  src/main/resources/sql/diplomas.sql
Labels: enhancement

#37 Bug with variables
  src/main/java/db/configuration/DataSourceConfig.java
  src/main/java/db/entities/Variable.java
  src/main/java/db/mapper/VariableMapper.java
  src/main/java/db/services/VariableService.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/controllers/FXMLVariablesController.java
  src/main/java/ui/models/Group.java
  src/main/java/ui/models/Variable.java
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/variables.fxml
  src/main/resources/sql/db.sql
  src/main/resources/sql/general_data.sql
Labels: bug

#38 Deputat
  src/main/java/db/entities/Variable.java
  src/main/java/db/mapper/VariableMapper.java
  src/main/java/doc_utils/DocWorker.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/resources/fxml/main.fxml
  src/main/resources/fxml/settings.fxml
  src/test/java/db/services/AccessRequirementsServiceTest.java
Labels: enhancement

#39 Some changes, master's db added
  master_diploma.db
  src/main/java/db/configurations/DataSourceConfig.java
  src/main/java/db/entities/Variable.java
  src/main/java/db/mappers/AccessRequirementsMapper.java
  src/main/java/db/mappers/ClassificationSystemMapper.java
  src/main/java/db/mappers/DiplomaMapper.java
  src/main/java/db/mappers/DiplomaSubjectMapper.java
  src/main/java/db/mappers/DurationOfStudyMapper.java
  src/main/java/db/mappers/DurationOfTrainingMapper.java
  src/main/java/db/mappers/EctsCreditsMapper.java
  src/main/java/db/mappers/EducationalComponentMapper.java
  src/main/java/db/mappers/EducationalComponentTemplateMapMapper.java
  src/main/java/db/mappers/EducationalComponentTemplateMapper.java
  src/main/java/db/mappers/EducationalComponentTypeMapper.java
  src/main/java/db/mappers/FieldOfStudyMapper.java
  src/main/java/db/mappers/GroupMapper.java
  src/main/java/db/mappers/MainFieldMapper.java
  src/main/java/db/mappers/Mapper.java
  src/main/java/db/mappers/ModeOfStudyMapper.java
  src/main/java/db/mappers/NationalGradeMapper.java
  src/main/java/db/mappers/OfficialDurationOfProgrammeMapper.java
  src/main/java/db/mappers/PreviousDocumentMapper.java
  src/main/java/db/mappers/ProtocolMapper.java
  src/main/java/db/mappers/RatingPointMapper.java
  src/main/java/db/mappers/StudentMapper.java
  src/main/java/db/mappers/VariableMapper.java
  src/main/java/ui/Main.java
  src/main/java/ui/controllers/FXMLEducationalComponentsController.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/java/ui/controllers/FXMLStudentController.java
  src/main/java/ui/controllers/FXMLVariablesController.java
  src/main/java/ui/utils/AppConfig.java
  src/main/resources/bachelor_sql/db.sql
  src/main/resources/bachelor_sql/diploma_subjects.sql
  src/main/resources/bachelor_sql/diplomas.sql
  src/main/resources/bachelor_sql/drop.sql
  src/main/resources/bachelor_sql/educational_components(PI-14-1).sql
  src/main/resources/bachelor_sql/educational_components(PIt-15-2).sql
  src/main/resources/bachelor_sql/educational_components(PIt-16-3).sql
  src/main/resources/bachelor_sql/educational_components(PIt-16-4).sql
  src/main/resources/bachelor_sql/educational_components(PIz-14-1).sql
  src/main/resources/bachelor_sql/educational_components(UPDATE national grade).sql
  src/main/resources/bachelor_sql/educational_components_template.sql
  src/main/resources/bachelor_sql/general_data.sql
  src/main/resources/bachelor_sql/previous_document.sql
  src/main/resources/bachelor_sql/protocols_TEST.sql
  src/main/resources/bachelor_sql/students.sql
  src/main/resources/database.properties
  src/main/resources/doc.properties
  src/main/resources/master_sql/db.sql
  src/main/resources/master_sql/drop.sql
  src/main/resources/master_sql/general_data.sql
  src/main/resources/ui.properties
  src/test/java/db/services/AccessRequirementsServiceTest.java
Labels: bug, enhancement

#40 Deputat
  src/main/java/ui/controllers/FXMLEducationalComponentsController.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/utils/AppConfig.java
  src/main/java/ui/utils/ProgressForm.java
  src/main/resources/bachelor_sql/diploma_subjects.sql
  src/main/resources/sql/master/general_data.sql
Labels: enhancement

#41 Deputat
  build.gradle
  src/main/java/db/configurations/DataSourceConfig.java
  src/main/java/db/services/TableCleanerService.java
  src/main/java/doc_utils/AppProperties.java
  src/main/java/doc_utils/DocWorker.java
  src/main/java/ui/controllers/FXMLEducationalComponentsController.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/utils/AppConfig.java
  src/main/resources/bachelor_sql/diploma_subjects.sql
  src/main/resources/bachelor_sql/drop.sql
  src/main/resources/bachelor_sql/educational_components(PI-14-1).sql
  src/main/resources/database.properties
  src/main/resources/doc.properties
  src/main/resources/fxml/main.fxml
Labels: enhancement

#42 Final commit
  master_diploma.db
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/controllers/FXMLSettingsController.java
  src/main/resources/fxml/settings.fxml
  src/main/resources/fxml/student.fxml
  src/main/resources/sql/master/general_data.sql
Labels: enhancement

#43 Deputat
  src/main/java/db/configurations/DataSourceConfig.java
  src/main/java/db/services/EducationalComponentService.java
  src/main/java/doc_utils/AppProperties.java
  src/main/java/doc_utils/DocVariableConst.java
  src/main/java/doc_utils/DocWorker.java
  src/main/java/ui/controllers/FXMLAVGController.java
  src/main/java/ui/controllers/FXMLMainController.java
  src/main/java/ui/models/StudentWithAVG.java
  src/main/resources/database.properties
  src/main/resources/doc.properties
  src/main/resources/fxml/avg.fxml
  src/main/resources/fxml/main.fxml
Labels: enhancement

#44 minor changes
  src/main/resources/fxml/avg.fxml
Labels: bug
